-- Highly divisible triangular number
-- Problem 12
--
-- The sequence of triangle numbers is generated by adding the natural numbers.
-- So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The
-- first ten terms would be:
--
-- 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
--
-- Let us list the factors of the first seven triangle numbers:
--
--  1: 1
--  3: 1,3
--  6: 1,2,3,6
-- 10: 1,2,5,10
-- 15: 1,3,5,15
-- 21: 1,3,7,21
-- 28: 1,2,4,7,14,28
--
-- We can see that 28 is the first triangle number to have over five divisors.
--
-- What is the value of the first triangle number to have over five hundred
-- divisors?

{-# OPTIONS_GHC -O2 #-}

triangle :: [Integer]
triangle = map fst $ iterate (\(a, b) -> (a + b, b + 1)) (1, 2)

divLen :: Integer -> Integer
divLen n = foldr (\e r -> if n `mod` e == 0 then r+1 else r) 2 [2..(n `div` 2)]

main = print $ head [x | x <- triangle, divLen x > 500]

