-- Triangular, pentagonal, and hexagonal
-- Problem 45
--
-- Triangle, pentagonal, and hexagonal numbers are generated by the following
-- formulae:
--
-- Triangle       Tn=n(n+1)/2       1, 3, 6, 10, 15, ...
-- Pentagonal     Pn=n(3n−1)/2      1, 5, 12, 22, 35, ...
-- Hexagonal      Hn=n(2n−1  )      1, 6, 15, 28, 45, ...
--
-- It can be verified that T285 = P165 = H143 = 40755.
--
-- Find the next triangle number that is also pentagonal and hexagonal.

{-# OPTIONS_GHC -O2 #-}

triangle :: [Int]
triangle = map round $ map fst $ iterate (\(a,c) -> (c/2*(c+1), c+1)) (1,2)

pentagonal :: [Int]
pentagonal = map round $ map fst $ iterate (\(a,c) -> (c/2*(3*c-1), c+1)) (1,2)

hexagonal :: [Int]
hexagonal = map round $ map fst $ iterate (\(a,c) -> (c*(2*c-1), c+1)) (1,2)

risingElem :: (Ord a, Eq a) => [a] -> a -> Bool
risingElem l n = elem n (takeWhile (<= n) l)

main = print $ [x | x <- hexagonal, risingElem pentagonal x, risingElem hexagonal x] !! 3

